// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// OnlineMeetingCollectionCreateOrGetRequestParameter undocumented
type OnlineMeetingCollectionCreateOrGetRequestParameter struct {
	// ChatInfo undocumented
	ChatInfo *ChatInfo `json:"chatInfo,omitempty"`
	// EndDateTime undocumented
	EndDateTime *time.Time `json:"endDateTime,omitempty"`
	// ExternalID undocumented
	ExternalID *string `json:"externalId,omitempty"`
	// Participants undocumented
	Participants *MeetingParticipants `json:"participants,omitempty"`
	// StartDateTime undocumented
	StartDateTime *time.Time `json:"startDateTime,omitempty"`
	// Subject undocumented
	Subject *string `json:"subject,omitempty"`
}
