// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// RoutingType undocumented
type RoutingType string

const (
	// RoutingTypeVForwarded undocumented
	RoutingTypeVForwarded RoutingType = "forwarded"
	// RoutingTypeVLookup undocumented
	RoutingTypeVLookup RoutingType = "lookup"
	// RoutingTypeVSelfFork undocumented
	RoutingTypeVSelfFork RoutingType = "selfFork"
	// RoutingTypeVUnknownFutureValue undocumented
	RoutingTypeVUnknownFutureValue RoutingType = "unknownFutureValue"
)

var (
	// RoutingTypePForwarded is a pointer to RoutingTypeVForwarded
	RoutingTypePForwarded = &_RoutingTypePForwarded
	// RoutingTypePLookup is a pointer to RoutingTypeVLookup
	RoutingTypePLookup = &_RoutingTypePLookup
	// RoutingTypePSelfFork is a pointer to RoutingTypeVSelfFork
	RoutingTypePSelfFork = &_RoutingTypePSelfFork
	// RoutingTypePUnknownFutureValue is a pointer to RoutingTypeVUnknownFutureValue
	RoutingTypePUnknownFutureValue = &_RoutingTypePUnknownFutureValue
)

var (
	_RoutingTypePForwarded          = RoutingTypeVForwarded
	_RoutingTypePLookup             = RoutingTypeVLookup
	_RoutingTypePSelfFork           = RoutingTypeVSelfFork
	_RoutingTypePUnknownFutureValue = RoutingTypeVUnknownFutureValue
)
