// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// EntityType undocumented
type EntityType string

const (
	// EntityTypeVEvent undocumented
	EntityTypeVEvent EntityType = "event"
	// EntityTypeVMessage undocumented
	EntityTypeVMessage EntityType = "message"
	// EntityTypeVDriveItem undocumented
	EntityTypeVDriveItem EntityType = "driveItem"
	// EntityTypeVExternalItem undocumented
	EntityTypeVExternalItem EntityType = "externalItem"
	// EntityTypeVSite undocumented
	EntityTypeVSite EntityType = "site"
	// EntityTypeVList undocumented
	EntityTypeVList EntityType = "list"
	// EntityTypeVListItem undocumented
	EntityTypeVListItem EntityType = "listItem"
	// EntityTypeVDrive undocumented
	EntityTypeVDrive EntityType = "drive"
	// EntityTypeVUnknownfuturevalue undocumented
	EntityTypeVUnknownfuturevalue EntityType = "unknownfuturevalue"
)

var (
	// EntityTypePEvent is a pointer to EntityTypeVEvent
	EntityTypePEvent = &_EntityTypePEvent
	// EntityTypePMessage is a pointer to EntityTypeVMessage
	EntityTypePMessage = &_EntityTypePMessage
	// EntityTypePDriveItem is a pointer to EntityTypeVDriveItem
	EntityTypePDriveItem = &_EntityTypePDriveItem
	// EntityTypePExternalItem is a pointer to EntityTypeVExternalItem
	EntityTypePExternalItem = &_EntityTypePExternalItem
	// EntityTypePSite is a pointer to EntityTypeVSite
	EntityTypePSite = &_EntityTypePSite
	// EntityTypePList is a pointer to EntityTypeVList
	EntityTypePList = &_EntityTypePList
	// EntityTypePListItem is a pointer to EntityTypeVListItem
	EntityTypePListItem = &_EntityTypePListItem
	// EntityTypePDrive is a pointer to EntityTypeVDrive
	EntityTypePDrive = &_EntityTypePDrive
	// EntityTypePUnknownfuturevalue is a pointer to EntityTypeVUnknownfuturevalue
	EntityTypePUnknownfuturevalue = &_EntityTypePUnknownfuturevalue
)

var (
	_EntityTypePEvent              = EntityTypeVEvent
	_EntityTypePMessage            = EntityTypeVMessage
	_EntityTypePDriveItem          = EntityTypeVDriveItem
	_EntityTypePExternalItem       = EntityTypeVExternalItem
	_EntityTypePSite               = EntityTypeVSite
	_EntityTypePList               = EntityTypeVList
	_EntityTypePListItem           = EntityTypeVListItem
	_EntityTypePDrive              = EntityTypeVDrive
	_EntityTypePUnknownfuturevalue = EntityTypeVUnknownfuturevalue
)
