// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// LobbyBypassScope undocumented
type LobbyBypassScope string

const (
	// LobbyBypassScopeVOrganizer undocumented
	LobbyBypassScopeVOrganizer LobbyBypassScope = "organizer"
	// LobbyBypassScopeVOrganization undocumented
	LobbyBypassScopeVOrganization LobbyBypassScope = "organization"
	// LobbyBypassScopeVOrganizationAndFederated undocumented
	LobbyBypassScopeVOrganizationAndFederated LobbyBypassScope = "organizationAndFederated"
	// LobbyBypassScopeVEveryone undocumented
	LobbyBypassScopeVEveryone LobbyBypassScope = "everyone"
	// LobbyBypassScopeVUnknownFutureValue undocumented
	LobbyBypassScopeVUnknownFutureValue LobbyBypassScope = "unknownFutureValue"
)

var (
	// LobbyBypassScopePOrganizer is a pointer to LobbyBypassScopeVOrganizer
	LobbyBypassScopePOrganizer = &_LobbyBypassScopePOrganizer
	// LobbyBypassScopePOrganization is a pointer to LobbyBypassScopeVOrganization
	LobbyBypassScopePOrganization = &_LobbyBypassScopePOrganization
	// LobbyBypassScopePOrganizationAndFederated is a pointer to LobbyBypassScopeVOrganizationAndFederated
	LobbyBypassScopePOrganizationAndFederated = &_LobbyBypassScopePOrganizationAndFederated
	// LobbyBypassScopePEveryone is a pointer to LobbyBypassScopeVEveryone
	LobbyBypassScopePEveryone = &_LobbyBypassScopePEveryone
	// LobbyBypassScopePUnknownFutureValue is a pointer to LobbyBypassScopeVUnknownFutureValue
	LobbyBypassScopePUnknownFutureValue = &_LobbyBypassScopePUnknownFutureValue
)

var (
	_LobbyBypassScopePOrganizer                = LobbyBypassScopeVOrganizer
	_LobbyBypassScopePOrganization             = LobbyBypassScopeVOrganization
	_LobbyBypassScopePOrganizationAndFederated = LobbyBypassScopeVOrganizationAndFederated
	_LobbyBypassScopePEveryone                 = LobbyBypassScopeVEveryone
	_LobbyBypassScopePUnknownFutureValue       = LobbyBypassScopeVUnknownFutureValue
)
