// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// AuthenticatorAppFeatureSettings undocumented
type AuthenticatorAppFeatureSettings string

const (
	// AuthenticatorAppFeatureSettingsVRequireNumberMatching undocumented
	AuthenticatorAppFeatureSettingsVRequireNumberMatching AuthenticatorAppFeatureSettings = "requireNumberMatching"
)

var (
	// AuthenticatorAppFeatureSettingsPRequireNumberMatching is a pointer to AuthenticatorAppFeatureSettingsVRequireNumberMatching
	AuthenticatorAppFeatureSettingsPRequireNumberMatching = &_AuthenticatorAppFeatureSettingsPRequireNumberMatching
)

var (
	_AuthenticatorAppFeatureSettingsPRequireNumberMatching = AuthenticatorAppFeatureSettingsVRequireNumberMatching
)
