// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// TeamworkActivityTopicSource undocumented
type TeamworkActivityTopicSource string

const (
	// TeamworkActivityTopicSourceVEntityURL undocumented
	TeamworkActivityTopicSourceVEntityURL TeamworkActivityTopicSource = "entityUrl"
	// TeamworkActivityTopicSourceVText undocumented
	TeamworkActivityTopicSourceVText TeamworkActivityTopicSource = "text"
)

var (
	// TeamworkActivityTopicSourcePEntityURL is a pointer to TeamworkActivityTopicSourceVEntityURL
	TeamworkActivityTopicSourcePEntityURL = &_TeamworkActivityTopicSourcePEntityURL
	// TeamworkActivityTopicSourcePText is a pointer to TeamworkActivityTopicSourceVText
	TeamworkActivityTopicSourcePText = &_TeamworkActivityTopicSourcePText
)

var (
	_TeamworkActivityTopicSourcePEntityURL = TeamworkActivityTopicSourceVEntityURL
	_TeamworkActivityTopicSourcePText      = TeamworkActivityTopicSourceVText
)
