// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// AuthenticationMethodKeyStrength undocumented
type AuthenticationMethodKeyStrength string

const (
	// AuthenticationMethodKeyStrengthVNormal undocumented
	AuthenticationMethodKeyStrengthVNormal AuthenticationMethodKeyStrength = "normal"
	// AuthenticationMethodKeyStrengthVWeak undocumented
	AuthenticationMethodKeyStrengthVWeak AuthenticationMethodKeyStrength = "weak"
	// AuthenticationMethodKeyStrengthVUnknown undocumented
	AuthenticationMethodKeyStrengthVUnknown AuthenticationMethodKeyStrength = "unknown"
)

var (
	// AuthenticationMethodKeyStrengthPNormal is a pointer to AuthenticationMethodKeyStrengthVNormal
	AuthenticationMethodKeyStrengthPNormal = &_AuthenticationMethodKeyStrengthPNormal
	// AuthenticationMethodKeyStrengthPWeak is a pointer to AuthenticationMethodKeyStrengthVWeak
	AuthenticationMethodKeyStrengthPWeak = &_AuthenticationMethodKeyStrengthPWeak
	// AuthenticationMethodKeyStrengthPUnknown is a pointer to AuthenticationMethodKeyStrengthVUnknown
	AuthenticationMethodKeyStrengthPUnknown = &_AuthenticationMethodKeyStrengthPUnknown
)

var (
	_AuthenticationMethodKeyStrengthPNormal  = AuthenticationMethodKeyStrengthVNormal
	_AuthenticationMethodKeyStrengthPWeak    = AuthenticationMethodKeyStrengthVWeak
	_AuthenticationMethodKeyStrengthPUnknown = AuthenticationMethodKeyStrengthVUnknown
)

// AuthenticationMethodState undocumented
type AuthenticationMethodState string

const (
	// AuthenticationMethodStateVEnabled undocumented
	AuthenticationMethodStateVEnabled AuthenticationMethodState = "enabled"
	// AuthenticationMethodStateVDisabled undocumented
	AuthenticationMethodStateVDisabled AuthenticationMethodState = "disabled"
)

var (
	// AuthenticationMethodStatePEnabled is a pointer to AuthenticationMethodStateVEnabled
	AuthenticationMethodStatePEnabled = &_AuthenticationMethodStatePEnabled
	// AuthenticationMethodStatePDisabled is a pointer to AuthenticationMethodStateVDisabled
	AuthenticationMethodStatePDisabled = &_AuthenticationMethodStatePDisabled
)

var (
	_AuthenticationMethodStatePEnabled  = AuthenticationMethodStateVEnabled
	_AuthenticationMethodStatePDisabled = AuthenticationMethodStateVDisabled
)

// AuthenticationMethodTargetType undocumented
type AuthenticationMethodTargetType string

const (
	// AuthenticationMethodTargetTypeVUser undocumented
	AuthenticationMethodTargetTypeVUser AuthenticationMethodTargetType = "user"
	// AuthenticationMethodTargetTypeVGroup undocumented
	AuthenticationMethodTargetTypeVGroup AuthenticationMethodTargetType = "group"
	// AuthenticationMethodTargetTypeVUnknownFutureValue undocumented
	AuthenticationMethodTargetTypeVUnknownFutureValue AuthenticationMethodTargetType = "unknownFutureValue"
)

var (
	// AuthenticationMethodTargetTypePUser is a pointer to AuthenticationMethodTargetTypeVUser
	AuthenticationMethodTargetTypePUser = &_AuthenticationMethodTargetTypePUser
	// AuthenticationMethodTargetTypePGroup is a pointer to AuthenticationMethodTargetTypeVGroup
	AuthenticationMethodTargetTypePGroup = &_AuthenticationMethodTargetTypePGroup
	// AuthenticationMethodTargetTypePUnknownFutureValue is a pointer to AuthenticationMethodTargetTypeVUnknownFutureValue
	AuthenticationMethodTargetTypePUnknownFutureValue = &_AuthenticationMethodTargetTypePUnknownFutureValue
)

var (
	_AuthenticationMethodTargetTypePUser               = AuthenticationMethodTargetTypeVUser
	_AuthenticationMethodTargetTypePGroup              = AuthenticationMethodTargetTypeVGroup
	_AuthenticationMethodTargetTypePUnknownFutureValue = AuthenticationMethodTargetTypeVUnknownFutureValue
)
