// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// InformationProtection undocumented
type InformationProtection struct {
	// Entity is the base model of InformationProtection
	Entity
	// ThreatAssessmentRequests undocumented
	ThreatAssessmentRequests []ThreatAssessmentRequestObject `json:"threatAssessmentRequests,omitempty"`
}
