// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// RequestObject undocumented
type RequestObject struct {
	// Entity is the base model of RequestObject
	Entity
	// ApprovalID undocumented
	ApprovalID *string `json:"approvalId,omitempty"`
	// CompletedDateTime undocumented
	CompletedDateTime *time.Time `json:"completedDateTime,omitempty"`
	// CreatedBy undocumented
	CreatedBy *IdentitySet `json:"createdBy,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// CustomData undocumented
	CustomData *string `json:"customData,omitempty"`
	// Status undocumented
	Status *string `json:"status,omitempty"`
}
