// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// MeetingInfo undocumented
type MeetingInfo struct {
	// Object is the base model of MeetingInfo
	Object
}

// MeetingParticipantInfo undocumented
type MeetingParticipantInfo struct {
	// Object is the base model of MeetingParticipantInfo
	Object
	// Identity undocumented
	Identity *IdentitySet `json:"identity,omitempty"`
	// Role undocumented
	Role *OnlineMeetingRole `json:"role,omitempty"`
	// Upn undocumented
	Upn *string `json:"upn,omitempty"`
}

// MeetingParticipants undocumented
type MeetingParticipants struct {
	// Object is the base model of MeetingParticipants
	Object
	// Attendees undocumented
	Attendees []MeetingParticipantInfo `json:"attendees,omitempty"`
	// Organizer undocumented
	Organizer *MeetingParticipantInfo `json:"organizer,omitempty"`
}

// MeetingTimeSuggestion undocumented
type MeetingTimeSuggestion struct {
	// Object is the base model of MeetingTimeSuggestion
	Object
	// AttendeeAvailability undocumented
	AttendeeAvailability []AttendeeAvailability `json:"attendeeAvailability,omitempty"`
	// Confidence undocumented
	Confidence *float64 `json:"confidence,omitempty"`
	// Locations undocumented
	Locations []Location `json:"locations,omitempty"`
	// MeetingTimeSlot undocumented
	MeetingTimeSlot *TimeSlot `json:"meetingTimeSlot,omitempty"`
	// Order undocumented
	Order *int `json:"order,omitempty"`
	// OrganizerAvailability undocumented
	OrganizerAvailability *FreeBusyStatus `json:"organizerAvailability,omitempty"`
	// SuggestionReason undocumented
	SuggestionReason *string `json:"suggestionReason,omitempty"`
}

// MeetingTimeSuggestionsResult undocumented
type MeetingTimeSuggestionsResult struct {
	// Object is the base model of MeetingTimeSuggestionsResult
	Object
	// EmptySuggestionsReason undocumented
	EmptySuggestionsReason *string `json:"emptySuggestionsReason,omitempty"`
	// MeetingTimeSuggestions undocumented
	MeetingTimeSuggestions []MeetingTimeSuggestion `json:"meetingTimeSuggestions,omitempty"`
}
