// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// MailboxSettings undocumented
type MailboxSettings struct {
	// Object is the base model of MailboxSettings
	Object
	// ArchiveFolder undocumented
	ArchiveFolder *string `json:"archiveFolder,omitempty"`
	// AutomaticRepliesSetting undocumented
	AutomaticRepliesSetting *AutomaticRepliesSetting `json:"automaticRepliesSetting,omitempty"`
	// DateFormat undocumented
	DateFormat *string `json:"dateFormat,omitempty"`
	// DelegateMeetingMessageDeliveryOptions undocumented
	DelegateMeetingMessageDeliveryOptions *DelegateMeetingMessageDeliveryOptions `json:"delegateMeetingMessageDeliveryOptions,omitempty"`
	// Language undocumented
	Language *LocaleInfo `json:"language,omitempty"`
	// TimeFormat undocumented
	TimeFormat *string `json:"timeFormat,omitempty"`
	// TimeZone undocumented
	TimeZone *string `json:"timeZone,omitempty"`
	// WorkingHours undocumented
	WorkingHours *WorkingHours `json:"workingHours,omitempty"`
}
