// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SamlSingleSignOnSettings undocumented
type SamlSingleSignOnSettings struct {
	// Object is the base model of SamlSingleSignOnSettings
	Object
	// RelayState undocumented
	RelayState *string `json:"relayState,omitempty"`
}
