// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Call undocumented
type Call struct {
	// Entity is the base model of Call
	Entity
	// CallbackURI undocumented
	CallbackURI *string `json:"callbackUri,omitempty"`
	// CallChainID undocumented
	CallChainID *string `json:"callChainId,omitempty"`
	// CallOptions undocumented
	CallOptions *CallOptions `json:"callOptions,omitempty"`
	// CallRoutes undocumented
	CallRoutes []CallRoute `json:"callRoutes,omitempty"`
	// ChatInfo undocumented
	ChatInfo *ChatInfo `json:"chatInfo,omitempty"`
	// Direction undocumented
	Direction *CallDirection `json:"direction,omitempty"`
	// IncomingContext undocumented
	IncomingContext *IncomingContext `json:"incomingContext,omitempty"`
	// MediaConfig undocumented
	MediaConfig *MediaConfig `json:"mediaConfig,omitempty"`
	// MediaState undocumented
	MediaState *CallMediaState `json:"mediaState,omitempty"`
	// MeetingInfo undocumented
	MeetingInfo *MeetingInfo `json:"meetingInfo,omitempty"`
	// MyParticipantID undocumented
	MyParticipantID *string `json:"myParticipantId,omitempty"`
	// RequestedModalities undocumented
	RequestedModalities []Modality `json:"requestedModalities,omitempty"`
	// ResultInfo undocumented
	ResultInfo *ResultInfo `json:"resultInfo,omitempty"`
	// Source undocumented
	Source *ParticipantInfo `json:"source,omitempty"`
	// State undocumented
	State *CallState `json:"state,omitempty"`
	// Subject undocumented
	Subject *string `json:"subject,omitempty"`
	// Targets undocumented
	Targets []InvitationParticipantInfo `json:"targets,omitempty"`
	// TenantID undocumented
	TenantID *string `json:"tenantId,omitempty"`
	// ToneInfo undocumented
	ToneInfo *ToneInfo `json:"toneInfo,omitempty"`
	// Transcription undocumented
	Transcription *CallTranscriptionInfo `json:"transcription,omitempty"`
	// Operations undocumented
	Operations []CommsOperation `json:"operations,omitempty"`
	// Participants undocumented
	Participants []Participant `json:"participants,omitempty"`
}

// CallMediaState undocumented
type CallMediaState struct {
	// Object is the base model of CallMediaState
	Object
	// Audio undocumented
	Audio *MediaState `json:"audio,omitempty"`
}

// CallOptions undocumented
type CallOptions struct {
	// Object is the base model of CallOptions
	Object
}

// CallRoute undocumented
type CallRoute struct {
	// Object is the base model of CallRoute
	Object
	// Final undocumented
	Final *IdentitySet `json:"final,omitempty"`
	// Original undocumented
	Original *IdentitySet `json:"original,omitempty"`
	// RoutingType undocumented
	RoutingType *RoutingType `json:"routingType,omitempty"`
}

// CallTranscriptionInfo undocumented
type CallTranscriptionInfo struct {
	// Object is the base model of CallTranscriptionInfo
	Object
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// State undocumented
	State *CallTranscriptionState `json:"state,omitempty"`
}
