// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// SelfServiceSignUpAuthenticationFlowConfiguration undocumented
type SelfServiceSignUpAuthenticationFlowConfiguration struct {
	// Object is the base model of SelfServiceSignUpAuthenticationFlowConfiguration
	Object
	// IsEnabled undocumented
	IsEnabled *bool `json:"isEnabled,omitempty"`
}
