// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Phone undocumented
type Phone struct {
	// Object is the base model of Phone
	Object
	// Language undocumented
	Language *string `json:"language,omitempty"`
	// Number undocumented
	Number *string `json:"number,omitempty"`
	// Region undocumented
	Region *string `json:"region,omitempty"`
	// Type undocumented
	Type *PhoneType `json:"type,omitempty"`
}
