// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// PolicyBase undocumented
type PolicyBase struct {
	// DirectoryObject is the base model of PolicyBase
	DirectoryObject
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
}

// PolicyRoot undocumented
type PolicyRoot struct {
	// Entity is the base model of PolicyRoot
	Entity
	// AuthenticationMethodsPolicy undocumented
	AuthenticationMethodsPolicy *AuthenticationMethodsPolicy `json:"authenticationMethodsPolicy,omitempty"`
	// AuthenticationFlowsPolicy undocumented
	AuthenticationFlowsPolicy *AuthenticationFlowsPolicy `json:"authenticationFlowsPolicy,omitempty"`
	// ActivityBasedTimeoutPolicies undocumented
	ActivityBasedTimeoutPolicies []ActivityBasedTimeoutPolicy `json:"activityBasedTimeoutPolicies,omitempty"`
	// AuthorizationPolicy undocumented
	AuthorizationPolicy *AuthorizationPolicy `json:"authorizationPolicy,omitempty"`
	// ClaimsMappingPolicies undocumented
	ClaimsMappingPolicies []ClaimsMappingPolicy `json:"claimsMappingPolicies,omitempty"`
	// HomeRealmDiscoveryPolicies undocumented
	HomeRealmDiscoveryPolicies []HomeRealmDiscoveryPolicy `json:"homeRealmDiscoveryPolicies,omitempty"`
	// PermissionGrantPolicies undocumented
	PermissionGrantPolicies []PermissionGrantPolicy `json:"permissionGrantPolicies,omitempty"`
	// TokenIssuancePolicies undocumented
	TokenIssuancePolicies []TokenIssuancePolicy `json:"tokenIssuancePolicies,omitempty"`
	// TokenLifetimePolicies undocumented
	TokenLifetimePolicies []TokenLifetimePolicy `json:"tokenLifetimePolicies,omitempty"`
	// FeatureRolloutPolicies undocumented
	FeatureRolloutPolicies []FeatureRolloutPolicy `json:"featureRolloutPolicies,omitempty"`
	// AdminConsentRequestPolicy undocumented
	AdminConsentRequestPolicy *AdminConsentRequestPolicy `json:"adminConsentRequestPolicy,omitempty"`
	// ConditionalAccessPolicies undocumented
	ConditionalAccessPolicies []ConditionalAccessPolicy `json:"conditionalAccessPolicies,omitempty"`
	// IdentitySecurityDefaultsEnforcementPolicy undocumented
	IdentitySecurityDefaultsEnforcementPolicy *IdentitySecurityDefaultsEnforcementPolicy `json:"identitySecurityDefaultsEnforcementPolicy,omitempty"`
}
