// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Approval undocumented
type Approval struct {
	// Entity is the base model of Approval
	Entity
	// Stages undocumented
	Stages []ApprovalStage `json:"stages,omitempty"`
}

// ApprovalStage undocumented
type ApprovalStage struct {
	// Entity is the base model of ApprovalStage
	Entity
	// AssignedToMe undocumented
	AssignedToMe *bool `json:"assignedToMe,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// Justification undocumented
	Justification *string `json:"justification,omitempty"`
	// ReviewedBy undocumented
	ReviewedBy *Identity `json:"reviewedBy,omitempty"`
	// ReviewedDateTime undocumented
	ReviewedDateTime *time.Time `json:"reviewedDateTime,omitempty"`
	// ReviewResult undocumented
	ReviewResult *string `json:"reviewResult,omitempty"`
	// Status undocumented
	Status *string `json:"status,omitempty"`
}
