// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Invitation undocumented
type Invitation struct {
	// Entity is the base model of Invitation
	Entity
	// InvitedUserDisplayName undocumented
	InvitedUserDisplayName *string `json:"invitedUserDisplayName,omitempty"`
	// InvitedUserEmailAddress undocumented
	InvitedUserEmailAddress *string `json:"invitedUserEmailAddress,omitempty"`
	// InvitedUserMessageInfo undocumented
	InvitedUserMessageInfo *InvitedUserMessageInfo `json:"invitedUserMessageInfo,omitempty"`
	// InvitedUserType undocumented
	InvitedUserType *string `json:"invitedUserType,omitempty"`
	// InviteRedeemURL undocumented
	InviteRedeemURL *string `json:"inviteRedeemUrl,omitempty"`
	// InviteRedirectURL undocumented
	InviteRedirectURL *string `json:"inviteRedirectUrl,omitempty"`
	// SendInvitationMessage undocumented
	SendInvitationMessage *bool `json:"sendInvitationMessage,omitempty"`
	// Status undocumented
	Status *string `json:"status,omitempty"`
	// InvitedUser undocumented
	InvitedUser *User `json:"invitedUser,omitempty"`
}

// InvitationParticipantInfo undocumented
type InvitationParticipantInfo struct {
	// Object is the base model of InvitationParticipantInfo
	Object
	// Identity undocumented
	Identity *IdentitySet `json:"identity,omitempty"`
	// ReplacesCallID undocumented
	ReplacesCallID *string `json:"replacesCallId,omitempty"`
}
