// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// ServiceHostedMediaConfig undocumented
type ServiceHostedMediaConfig struct {
	// MediaConfig is the base model of ServiceHostedMediaConfig
	MediaConfig
	// PreFetchMedia undocumented
	PreFetchMedia []MediaInfo `json:"preFetchMedia,omitempty"`
}

// ServicePlanInfo undocumented
type ServicePlanInfo struct {
	// Object is the base model of ServicePlanInfo
	Object
	// AppliesTo undocumented
	AppliesTo *string `json:"appliesTo,omitempty"`
	// ProvisioningStatus undocumented
	ProvisioningStatus *string `json:"provisioningStatus,omitempty"`
	// ServicePlanID undocumented
	ServicePlanID *UUID `json:"servicePlanId,omitempty"`
	// ServicePlanName undocumented
	ServicePlanName *string `json:"servicePlanName,omitempty"`
}

// ServicePrincipal undocumented
type ServicePrincipal struct {
	// DirectoryObject is the base model of ServicePrincipal
	DirectoryObject
	// AccountEnabled undocumented
	AccountEnabled *bool `json:"accountEnabled,omitempty"`
	// AddIns undocumented
	AddIns []AddIn `json:"addIns,omitempty"`
	// AlternativeNames undocumented
	AlternativeNames []string `json:"alternativeNames,omitempty"`
	// AppDescription undocumented
	AppDescription *string `json:"appDescription,omitempty"`
	// AppDisplayName undocumented
	AppDisplayName *string `json:"appDisplayName,omitempty"`
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
	// ApplicationTemplateID undocumented
	ApplicationTemplateID *string `json:"applicationTemplateId,omitempty"`
	// AppOwnerOrganizationID undocumented
	AppOwnerOrganizationID *UUID `json:"appOwnerOrganizationId,omitempty"`
	// AppRoleAssignmentRequired undocumented
	AppRoleAssignmentRequired *bool `json:"appRoleAssignmentRequired,omitempty"`
	// AppRoles undocumented
	AppRoles []AppRole `json:"appRoles,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// Homepage undocumented
	Homepage *string `json:"homepage,omitempty"`
	// Info undocumented
	Info *InformationalURL `json:"info,omitempty"`
	// KeyCredentials undocumented
	KeyCredentials []KeyCredential `json:"keyCredentials,omitempty"`
	// LoginURL undocumented
	LoginURL *string `json:"loginUrl,omitempty"`
	// LogoutURL undocumented
	LogoutURL *string `json:"logoutUrl,omitempty"`
	// Notes undocumented
	Notes *string `json:"notes,omitempty"`
	// NotificationEmailAddresses undocumented
	NotificationEmailAddresses []string `json:"notificationEmailAddresses,omitempty"`
	// OAuth2PermissionScopes undocumented
	OAuth2PermissionScopes []PermissionScope `json:"oauth2PermissionScopes,omitempty"`
	// PasswordCredentials undocumented
	PasswordCredentials []PasswordCredential `json:"passwordCredentials,omitempty"`
	// PreferredSingleSignOnMode undocumented
	PreferredSingleSignOnMode *string `json:"preferredSingleSignOnMode,omitempty"`
	// PreferredTokenSigningKeyThumbprint undocumented
	PreferredTokenSigningKeyThumbprint *string `json:"preferredTokenSigningKeyThumbprint,omitempty"`
	// ReplyUrls undocumented
	ReplyUrls []string `json:"replyUrls,omitempty"`
	// SamlSingleSignOnSettings undocumented
	SamlSingleSignOnSettings *SamlSingleSignOnSettings `json:"samlSingleSignOnSettings,omitempty"`
	// ServicePrincipalNames undocumented
	ServicePrincipalNames []string `json:"servicePrincipalNames,omitempty"`
	// ServicePrincipalType undocumented
	ServicePrincipalType *string `json:"servicePrincipalType,omitempty"`
	// SignInAudience undocumented
	SignInAudience *string `json:"signInAudience,omitempty"`
	// Tags undocumented
	Tags []string `json:"tags,omitempty"`
	// TokenEncryptionKeyID undocumented
	TokenEncryptionKeyID *UUID `json:"tokenEncryptionKeyId,omitempty"`
	// AppRoleAssignedTo undocumented
	AppRoleAssignedTo []AppRoleAssignment `json:"appRoleAssignedTo,omitempty"`
	// AppRoleAssignments undocumented
	AppRoleAssignments []AppRoleAssignment `json:"appRoleAssignments,omitempty"`
	// ClaimsMappingPolicies undocumented
	ClaimsMappingPolicies []ClaimsMappingPolicy `json:"claimsMappingPolicies,omitempty"`
	// CreatedObjects undocumented
	CreatedObjects []DirectoryObject `json:"createdObjects,omitempty"`
	// DelegatedPermissionClassifications undocumented
	DelegatedPermissionClassifications []DelegatedPermissionClassification `json:"delegatedPermissionClassifications,omitempty"`
	// Endpoints undocumented
	Endpoints []Endpoint `json:"endpoints,omitempty"`
	// HomeRealmDiscoveryPolicies undocumented
	HomeRealmDiscoveryPolicies []HomeRealmDiscoveryPolicy `json:"homeRealmDiscoveryPolicies,omitempty"`
	// MemberOf undocumented
	MemberOf []DirectoryObject `json:"memberOf,omitempty"`
	// OAuth2PermissionGrants undocumented
	OAuth2PermissionGrants []OAuth2PermissionGrant `json:"oauth2PermissionGrants,omitempty"`
	// OwnedObjects undocumented
	OwnedObjects []DirectoryObject `json:"ownedObjects,omitempty"`
	// Owners undocumented
	Owners []DirectoryObject `json:"owners,omitempty"`
	// TokenIssuancePolicies undocumented
	TokenIssuancePolicies []TokenIssuancePolicy `json:"tokenIssuancePolicies,omitempty"`
	// TokenLifetimePolicies undocumented
	TokenLifetimePolicies []TokenLifetimePolicy `json:"tokenLifetimePolicies,omitempty"`
	// TransitiveMemberOf undocumented
	TransitiveMemberOf []DirectoryObject `json:"transitiveMemberOf,omitempty"`
}

// ServicePrincipalIdentity undocumented
type ServicePrincipalIdentity struct {
	// Identity is the base model of ServicePrincipalIdentity
	Identity
	// AppID undocumented
	AppID *string `json:"appId,omitempty"`
}
