// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Authentication undocumented
type Authentication struct {
	// Entity is the base model of Authentication
	Entity
	// Fido2Methods undocumented
	Fido2Methods []Fido2AuthenticationMethod `json:"fido2Methods,omitempty"`
	// Methods undocumented
	Methods []AuthenticationMethod `json:"methods,omitempty"`
	// MicrosoftAuthenticatorMethods undocumented
	MicrosoftAuthenticatorMethods []MicrosoftAuthenticatorAuthenticationMethod `json:"microsoftAuthenticatorMethods,omitempty"`
	// WindowsHelloForBusinessMethods undocumented
	WindowsHelloForBusinessMethods []WindowsHelloForBusinessAuthenticationMethod `json:"windowsHelloForBusinessMethods,omitempty"`
}

// AuthenticationFlowsPolicy undocumented
type AuthenticationFlowsPolicy struct {
	// Entity is the base model of AuthenticationFlowsPolicy
	Entity
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// SelfServiceSignUp undocumented
	SelfServiceSignUp *SelfServiceSignUpAuthenticationFlowConfiguration `json:"selfServiceSignUp,omitempty"`
}

// AuthenticationMethod undocumented
type AuthenticationMethod struct {
	// Entity is the base model of AuthenticationMethod
	Entity
}

// AuthenticationMethodConfiguration undocumented
type AuthenticationMethodConfiguration struct {
	// Entity is the base model of AuthenticationMethodConfiguration
	Entity
	// State undocumented
	State *AuthenticationMethodState `json:"state,omitempty"`
}

// AuthenticationMethodTarget undocumented
type AuthenticationMethodTarget struct {
	// Entity is the base model of AuthenticationMethodTarget
	Entity
	// IsRegistrationRequired undocumented
	IsRegistrationRequired *bool `json:"isRegistrationRequired,omitempty"`
	// TargetType undocumented
	TargetType *AuthenticationMethodTargetType `json:"targetType,omitempty"`
}

// AuthenticationMethodsPolicy undocumented
type AuthenticationMethodsPolicy struct {
	// Entity is the base model of AuthenticationMethodsPolicy
	Entity
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// LastModifiedDateTime undocumented
	LastModifiedDateTime *time.Time `json:"lastModifiedDateTime,omitempty"`
	// PolicyVersion undocumented
	PolicyVersion *string `json:"policyVersion,omitempty"`
	// ReconfirmationInDays undocumented
	ReconfirmationInDays *int `json:"reconfirmationInDays,omitempty"`
	// AuthenticationMethodConfigurations undocumented
	AuthenticationMethodConfigurations []AuthenticationMethodConfiguration `json:"authenticationMethodConfigurations,omitempty"`
}
