// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Team undocumented
type Team struct {
	// Entity is the base model of Team
	Entity
	// Classification undocumented
	Classification *string `json:"classification,omitempty"`
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// FunSettings undocumented
	FunSettings *TeamFunSettings `json:"funSettings,omitempty"`
	// GuestSettings undocumented
	GuestSettings *TeamGuestSettings `json:"guestSettings,omitempty"`
	// InternalID undocumented
	InternalID *string `json:"internalId,omitempty"`
	// IsArchived undocumented
	IsArchived *bool `json:"isArchived,omitempty"`
	// MemberSettings undocumented
	MemberSettings *TeamMemberSettings `json:"memberSettings,omitempty"`
	// MessagingSettings undocumented
	MessagingSettings *TeamMessagingSettings `json:"messagingSettings,omitempty"`
	// Specialization undocumented
	Specialization *TeamSpecialization `json:"specialization,omitempty"`
	// Visibility undocumented
	Visibility *TeamVisibilityType `json:"visibility,omitempty"`
	// WebURL undocumented
	WebURL *string `json:"webUrl,omitempty"`
	// Schedule undocumented
	Schedule *Schedule `json:"schedule,omitempty"`
	// Channels undocumented
	Channels []Channel `json:"channels,omitempty"`
	// Group undocumented
	Group *Group `json:"group,omitempty"`
	// InstalledApps undocumented
	InstalledApps []TeamsAppInstallation `json:"installedApps,omitempty"`
	// Members undocumented
	Members []ConversationMember `json:"members,omitempty"`
	// Operations undocumented
	Operations []TeamsAsyncOperation `json:"operations,omitempty"`
	// PrimaryChannel undocumented
	PrimaryChannel *Channel `json:"primaryChannel,omitempty"`
	// Template undocumented
	Template *TeamsTemplate `json:"template,omitempty"`
}

// TeamClassSettings undocumented
type TeamClassSettings struct {
	// Object is the base model of TeamClassSettings
	Object
	// NotifyGuardiansAboutAssignments undocumented
	NotifyGuardiansAboutAssignments *bool `json:"notifyGuardiansAboutAssignments,omitempty"`
}

// TeamFunSettings undocumented
type TeamFunSettings struct {
	// Object is the base model of TeamFunSettings
	Object
	// AllowCustomMemes undocumented
	AllowCustomMemes *bool `json:"allowCustomMemes,omitempty"`
	// AllowGiphy undocumented
	AllowGiphy *bool `json:"allowGiphy,omitempty"`
	// AllowStickersAndMemes undocumented
	AllowStickersAndMemes *bool `json:"allowStickersAndMemes,omitempty"`
	// GiphyContentRating undocumented
	GiphyContentRating *GiphyRatingType `json:"giphyContentRating,omitempty"`
}

// TeamGuestSettings undocumented
type TeamGuestSettings struct {
	// Object is the base model of TeamGuestSettings
	Object
	// AllowCreateUpdateChannels undocumented
	AllowCreateUpdateChannels *bool `json:"allowCreateUpdateChannels,omitempty"`
	// AllowDeleteChannels undocumented
	AllowDeleteChannels *bool `json:"allowDeleteChannels,omitempty"`
}

// TeamMemberSettings undocumented
type TeamMemberSettings struct {
	// Object is the base model of TeamMemberSettings
	Object
	// AllowAddRemoveApps undocumented
	AllowAddRemoveApps *bool `json:"allowAddRemoveApps,omitempty"`
	// AllowCreatePrivateChannels undocumented
	AllowCreatePrivateChannels *bool `json:"allowCreatePrivateChannels,omitempty"`
	// AllowCreateUpdateChannels undocumented
	AllowCreateUpdateChannels *bool `json:"allowCreateUpdateChannels,omitempty"`
	// AllowCreateUpdateRemoveConnectors undocumented
	AllowCreateUpdateRemoveConnectors *bool `json:"allowCreateUpdateRemoveConnectors,omitempty"`
	// AllowCreateUpdateRemoveTabs undocumented
	AllowCreateUpdateRemoveTabs *bool `json:"allowCreateUpdateRemoveTabs,omitempty"`
	// AllowDeleteChannels undocumented
	AllowDeleteChannels *bool `json:"allowDeleteChannels,omitempty"`
}

// TeamMessagingSettings undocumented
type TeamMessagingSettings struct {
	// Object is the base model of TeamMessagingSettings
	Object
	// AllowChannelMentions undocumented
	AllowChannelMentions *bool `json:"allowChannelMentions,omitempty"`
	// AllowOwnerDeleteMessages undocumented
	AllowOwnerDeleteMessages *bool `json:"allowOwnerDeleteMessages,omitempty"`
	// AllowTeamMentions undocumented
	AllowTeamMentions *bool `json:"allowTeamMentions,omitempty"`
	// AllowUserDeleteMessages undocumented
	AllowUserDeleteMessages *bool `json:"allowUserDeleteMessages,omitempty"`
	// AllowUserEditMessages undocumented
	AllowUserEditMessages *bool `json:"allowUserEditMessages,omitempty"`
}
