// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// EmailAuthenticationMethodConfigurationRequestBuilder is request builder for EmailAuthenticationMethodConfiguration
type EmailAuthenticationMethodConfigurationRequestBuilder struct{ BaseRequestBuilder }

// Request returns EmailAuthenticationMethodConfigurationRequest
func (b *EmailAuthenticationMethodConfigurationRequestBuilder) Request() *EmailAuthenticationMethodConfigurationRequest {
	return &EmailAuthenticationMethodConfigurationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// EmailAuthenticationMethodConfigurationRequest is request for EmailAuthenticationMethodConfiguration
type EmailAuthenticationMethodConfigurationRequest struct{ BaseRequest }

// Get performs GET request for EmailAuthenticationMethodConfiguration
func (r *EmailAuthenticationMethodConfigurationRequest) Get(ctx context.Context) (resObj *EmailAuthenticationMethodConfiguration, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for EmailAuthenticationMethodConfiguration
func (r *EmailAuthenticationMethodConfigurationRequest) Update(ctx context.Context, reqObj *EmailAuthenticationMethodConfiguration) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for EmailAuthenticationMethodConfiguration
func (r *EmailAuthenticationMethodConfigurationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
