// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// DelegatedPermissionClassificationRequestBuilder is request builder for DelegatedPermissionClassification
type DelegatedPermissionClassificationRequestBuilder struct{ BaseRequestBuilder }

// Request returns DelegatedPermissionClassificationRequest
func (b *DelegatedPermissionClassificationRequestBuilder) Request() *DelegatedPermissionClassificationRequest {
	return &DelegatedPermissionClassificationRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// DelegatedPermissionClassificationRequest is request for DelegatedPermissionClassification
type DelegatedPermissionClassificationRequest struct{ BaseRequest }

// Get performs GET request for DelegatedPermissionClassification
func (r *DelegatedPermissionClassificationRequest) Get(ctx context.Context) (resObj *DelegatedPermissionClassification, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for DelegatedPermissionClassification
func (r *DelegatedPermissionClassificationRequest) Update(ctx context.Context, reqObj *DelegatedPermissionClassification) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for DelegatedPermissionClassification
func (r *DelegatedPermissionClassificationRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
