// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// ServicePrincipalRequestBuilder is request builder for ServicePrincipal
type ServicePrincipalRequestBuilder struct{ BaseRequestBuilder }

// Request returns ServicePrincipalRequest
func (b *ServicePrincipalRequestBuilder) Request() *ServicePrincipalRequest {
	return &ServicePrincipalRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ServicePrincipalRequest is request for ServicePrincipal
type ServicePrincipalRequest struct{ BaseRequest }

// Get performs GET request for ServicePrincipal
func (r *ServicePrincipalRequest) Get(ctx context.Context) (resObj *ServicePrincipal, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for ServicePrincipal
func (r *ServicePrincipalRequest) Update(ctx context.Context, reqObj *ServicePrincipal) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for ServicePrincipal
func (r *ServicePrincipalRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}

//
type ServicePrincipalAddKeyRequestBuilder struct{ BaseRequestBuilder }

// AddKey action undocumented
func (b *ServicePrincipalRequestBuilder) AddKey(reqObj *ServicePrincipalAddKeyRequestParameter) *ServicePrincipalAddKeyRequestBuilder {
	bb := &ServicePrincipalAddKeyRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/addKey"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type ServicePrincipalAddKeyRequest struct{ BaseRequest }

//
func (b *ServicePrincipalAddKeyRequestBuilder) Request() *ServicePrincipalAddKeyRequest {
	return &ServicePrincipalAddKeyRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *ServicePrincipalAddKeyRequest) Post(ctx context.Context) (resObj *KeyCredential, err error) {
	err = r.JSONRequest(ctx, "POST", "", r.requestObject, &resObj)
	return
}

//
type ServicePrincipalAddPasswordRequestBuilder struct{ BaseRequestBuilder }

// AddPassword action undocumented
func (b *ServicePrincipalRequestBuilder) AddPassword(reqObj *ServicePrincipalAddPasswordRequestParameter) *ServicePrincipalAddPasswordRequestBuilder {
	bb := &ServicePrincipalAddPasswordRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/addPassword"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type ServicePrincipalAddPasswordRequest struct{ BaseRequest }

//
func (b *ServicePrincipalAddPasswordRequestBuilder) Request() *ServicePrincipalAddPasswordRequest {
	return &ServicePrincipalAddPasswordRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *ServicePrincipalAddPasswordRequest) Post(ctx context.Context) (resObj *PasswordCredential, err error) {
	err = r.JSONRequest(ctx, "POST", "", r.requestObject, &resObj)
	return
}

//
type ServicePrincipalRemoveKeyRequestBuilder struct{ BaseRequestBuilder }

// RemoveKey action undocumented
func (b *ServicePrincipalRequestBuilder) RemoveKey(reqObj *ServicePrincipalRemoveKeyRequestParameter) *ServicePrincipalRemoveKeyRequestBuilder {
	bb := &ServicePrincipalRemoveKeyRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/removeKey"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type ServicePrincipalRemoveKeyRequest struct{ BaseRequest }

//
func (b *ServicePrincipalRemoveKeyRequestBuilder) Request() *ServicePrincipalRemoveKeyRequest {
	return &ServicePrincipalRemoveKeyRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *ServicePrincipalRemoveKeyRequest) Post(ctx context.Context) error {
	return r.JSONRequest(ctx, "POST", "", r.requestObject, nil)
}

//
type ServicePrincipalRemovePasswordRequestBuilder struct{ BaseRequestBuilder }

// RemovePassword action undocumented
func (b *ServicePrincipalRequestBuilder) RemovePassword(reqObj *ServicePrincipalRemovePasswordRequestParameter) *ServicePrincipalRemovePasswordRequestBuilder {
	bb := &ServicePrincipalRemovePasswordRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/removePassword"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type ServicePrincipalRemovePasswordRequest struct{ BaseRequest }

//
func (b *ServicePrincipalRemovePasswordRequestBuilder) Request() *ServicePrincipalRemovePasswordRequest {
	return &ServicePrincipalRemovePasswordRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject},
	}
}

//
func (r *ServicePrincipalRemovePasswordRequest) Post(ctx context.Context) error {
	return r.JSONRequest(ctx, "POST", "", r.requestObject, nil)
}
